### ISSUE TITLE
Nothing happens when Account Button clicked

### ISSUE THREAD

**Issue by boonrs** [swinter2011/franklin#4]
Nothing happens when account button is clicked in the upper right hand corner. 
_Tested in chrome & safari._

To recreate:
- [Log in](https://benjamin-franklin.herokuapp.com/login) 
- Click the **Account** button in the upper right hand corner  
  Result => nothing happens

**Comment by swinter2011** [comment]
OK - I think this is working now. Tested it in Chrome, Firefox and Safari. I also fixed the Sign In button. 

I was able to get my ruby version set.

The app is working the way I want it to except for the fact that I haven't been able to precompile assets without breaking the [Sisyphus Rails](https://github.com/dnoonan/sisyphus-rails) gem that remembers form values before they're submitted. Somehow I did this before because I had to originally precompile assets to get background images etc. on the site. One thought I had is maybe precompiling again duplicates files that confuses the Sisyphus stuff. Not sure what to do...
